### ISSUE TITLE
line 140: Syntax error while running kissmanga.py

### ISSUE THREAD

**Issue by csmborgaro** [Astrames/kissmanga-downloader#4]
```
File "kissmanga.py", line 140
    print('\n',"#"*50,"\n",sep='')
                              ^
SyntaxError: invalid syntax
```
I encountered this error while I'm at tutorial, I'm using python 3.7... did the problem occurred because i used 3.7 instead of the 3.6?

**Comment by langurmonkey** [comment]
At this point you may want to use my fork. The code is cleaned up, and with a sane CLI interface which makes it much easier to interact with. I opened a merge request more than a year ago but it's been ignored ever since.  The fork repository is [here](https://github.com/langurmonkey/kissmanga-downloader).

**Comment by csmborgaro** [comment]
> int you may want to use my fork. The code is cleaned up, and with a sane CLI interface which makes it much easier to interact with. I opened a merge request more than a year ago but it's been

alright I will try it thanks for sharing

**Comment by csmborgaro** [comment]
> At this point you may want to use my fork. The code is cleaned up, and with a sane CLI interface which makes it much easier to interact with. I opened a merge request more than a year ago but it's been ignored ever since. The fork repository is [here](https://github.com/langurmonkey/kissmanga-downloader).

I downloaded the chromedriver just as you asked, does it requires google chrome too? I'm using Brave Browser (which runs in chromium 81.0)
![image](https://user-images.githubusercontent.com/44487404/82886099-9ef57600-9f78-11ea-8cfa-65bbd0ed423b.png)

and what do i do next? i cant put anything in the chromedrive.exe 
![image](https://user-images.githubusercontent.com/44487404/82886215-cb10f700-9f78-11ea-9702-08aad4c01cd0.png)

**Comment by csmborgaro** [comment]
things got more complicated help pls i don't use linux so i dont understand now the updated readme

**Comment by Astrames** [comment]
Have you tried running the command,

`python kissmanga-download -h`?

What output does it show?

> does it requires google chrome too?

No, this script doesn't use Google Chrome, it only needs that `chromedriver.exe` file.


FYI: I have merged langurmonkey's PR with this repository, so now both are at the same stage. So, you can download this repository again if you wish to use it. (Might be a bit simpler to use if you're on Windows, and haven't used Linux)

**Comment by csmborgaro** [comment]
> Have you tried running the command,
> 
> python kissmanga-download -h?
> 
> What output does it show?

I just did
![image](https://user-images.githubusercontent.com/44487404/82890779-47a6d400-9f7f-11ea-9965-cd827dc9a401.png)


It's line 140 again, and i have the chromedriver.exe. and installed the python 3.6 too if it helps

**Comment by langurmonkey** [comment]
It works fine here with Python 3.8.3 and Arch Linux. Don't have windows, but I've got a strong feeling you are actually using Python 2.x, where `print` is still a statement. Can you do

``` terminal
$  python --version
```

to make sure you are using Python 3?

**Comment by csmborgaro** [comment]
> It works fine here with Python 3.8.3 and Arch Linux. Don't have windows, but I've got a strong feeling you are actually using Python 2.x, where `print` is still a statement. Can you do
> 
> ```
> $  python --version
> ```
> 
> to make sure you are using Python 3?

I just did what you said, 
![image](https://user-images.githubusercontent.com/44487404/82909272-a24e2900-9f9b-11ea-9ad4-b9bf2902f907.png)

it's strange though, I have 3.6 and 3.7 installed. just as said in the requirements.
I'll download the latest python and try again
![image](https://user-images.githubusercontent.com/44487404/82909521-f822d100-9f9b-11ea-80c7-44c5da18c602.png)

**Comment by langurmonkey** [comment]
Yeah, I don't know how it works on Windows specifically, but there must be a place where you can edit your `$PATH` environment variable. Maybe @Astrames can help out.

BTW, you don't need to attach screenshots. You can just copy-paste the output and format it as code. It is better for indexing and searching. See [here](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by Astrames** [comment]
> > It works fine here with Python 3.8.3 and Arch Linux. Don't have windows, but I've got a strong feeling you are actually using Python 2.x, where `print` is still a statement. Can you do
> > ```
> > $  python --version
> > ```
> > 
> > 
> > to make sure you are using Python 3?
> 
> I just did what you said,
> ![image](https://user-images.githubusercontent.com/44487404/82909272-a24e2900-9f9b-11ea-9ad4-b9bf2902f907.png)
> 
> it's strange though, I have 3.6 and 3.7 installed. just as said in the requirements.
> I'll download the latest python and try again
> ![image](https://user-images.githubusercontent.com/44487404/82909521-f822d100-9f9b-11ea-80c7-44c5da18c602.png)

I'm gonna guess that either

A) the path to python 2 is present higher up than python36 in your path environment.

B) maybe you enabled the checkbox thar said "add to path" when installing python 2; I'd recommend uninstalling python 2 and trying all this again

**Comment by csmborgaro** [comment]
uninstalling python 2 worked. and after reinstalling the required files it worked like a charm now. thanks!
```
usage: kissmanga-downloader [-h] [-o OUTPUT] -u URL -i INI -e END [--pdf] [--pdf_series] [--chapter_page]
                            [--delay DELAY] [--ow]

Batch-download chapters and series from Kissmanga

optional arguments:
  -h, --help            show this help message and exit
  -o OUTPUT, --output OUTPUT
                        Output folder path where the series folder will be created. Defaults to the current path from
                        which this script is run
  -u URL, --url URL     Name of the series, no need to include the base kissmanga URL, so for
                        'https://kissmanga.com/Manga/Dragon-Ball' use'Dragon-Ball)
  -i INI, --ini INI     Initial chapter number to download, in [1..n]
  -e END, --end END     Final chapter number to download, included
  --pdf                 Generate a PDF file for each chapter
  --pdf_series          Generate a huge PDF file with all chapters
  --chapter_page        Render a chapter page and put it in front of the PDDF of each chapter
  --delay DELAY         Add a delay (in seconds) between page downloads to avoid overloading the server
  --ow                  Overwrite existing PDF files

C:\Users\Loli\Desktop\kissmanga-downloader-master>
```
